name: Entregables

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4
      - name: Paso 2 - Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
      - name: Paso 3 - Crear entorno virtual
        run: python -m venv venv
      - name: Paso 4 - Activar entorno virtual
        run: ./venv/Scripts/activate
      - name: Paso 5 - Actualizar pip
        run: pip install --upgrade pip
      - name: Paso 6 - Instalar dependecias
        run: pip install -e .
      - name: Paso 5 - Ejecutar Script
        run: python src/edu_bigdata/main.py
      - name: Paso 6 - crear commit automatico
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Entrega de la actividad 1
          commit_user_name: Oscar Mantilla [GitHub Actions]
          commit_user_email: oscar.mantilla@est.iudigital.edu.co
          commit_author: Oscar Mantilla <oscar.mantilla@est.iudigital.edu.co>
